<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\HQVerse.Domain\HQVerse.Domain.csproj" />
    <ProjectReference Include="..\HQVerse.Application\HQVerse.Application.csproj" />
    <ProjectReference Include="..\HQVerse.Infrastructure\HQVerse.Infrastructure.csproj" />
    <ProjectReference Include="..\HQVerse.CrossCutting\HQVerse.CrossCutting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.1.13" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.PostgreSQL" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <UserSecretsId>bebdde2a-32d3-4534-8a36-6b0b0b4d9567</UserSecretsId>
  </PropertyGroup>

</Project>
